name = "homelab-pages"
compatibility_date = "2024-01-01"

# Custom domain configuration
[env.production]
name = "homelab-pages"
route = { pattern = "homelab.pages.danielbooth.cloud", zone_name = "danielbooth.cloud" }